---
- name: IOS Example
  hosts: pynet-rtr1
  vars:
    creds:
      host: 184.105.247.70
      username: pyclass
      password: invalid
  tasks:
    - ios_facts:
        provider: "{{ creds }}"

