---
- name: IOS Example
  hosts: cisco
  tasks:
    - name: Test IOS
      ios_facts:
        provider: "{{ creds_core_ssh }}"
      tags: facts_only

    - name: String literal, not variable
      debug:
        msg: ansible_net_model

