---
- name: Invalid Password
  hosts: cisco
  vars:
    creds_core_broke:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "bogus"
      timeout: 60
  tasks:
    - name: Test IOS
      ios_facts:
        provider: "{{ creds_core_broke }}"
      tags: facts_only

    - debug:
        msg: "{{ ansible_net_model }}"

