---
- name: NAPALM PING
  hosts: cisco
  tasks:
    - name: NAPALM ping
      napalm_ping: 
        hostname: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        dev_os: "ios"
        destination: 10.220.88.1
