---
- name: EOS Config Vlans
  hosts: pynet-sw5
  gather_facts: False
  vars:
    gateway: 10.220.88.1
  tasks:
    - eos_config:
        provider: "{{ creds_eapi }}"
        lines: 
          - "ip route 1.1.1.1/32 {{ gateway }}"
          - "ip route 1.1.1.2/32 {{ gateway }}"
          - "ip route 1.1.1.3/32 {{ gateway }}"
          - "ip route 1.1.1.4/32 {{ gateway }}"
